name: Push to Mailgun
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v3

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Start
        run: yarn start
        env:
          CI: true
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          NODE_ENV: production
